### ISSUE TITLE
Waad

### ISSUE THREAD

**Issue by WaadAB** [js-penguins/JS-final-project#1]
Name of your app (Personal Diary )
What the app will do? user will be able to add and remove task in her/his to do list.
What API will you use?  Unsplash API, use it for having amazed photo for background. 
Link to the documentation
An example endpoint
What data will you use from it? photos key to have it as background
Anything else that will help us understand what you are creating! more things may come to my brain while I'am in progress.

**Comment by trevorpreston** [comment]
Sounds good.  I would like to see you do something with the API that is different than what we did with Momentum.  For example, maybe the user can select a theme like "sunset photos" and it picks a random sunset photo?  That's just an idea, but it would be nice to have some kind of input from the user that results in a photo from Unsplash.

Approval pending.  Let me know what you are thinking!

**Comment by WaadAB** [comment]
Name of your app  (Book store)
What the app will do? the app is represent book's information by given ISBN.
What API will you use? Include: use Google Books API 
a link to the documentation : https://developers.google.com/books/docs/v1/using
an example endpoint : using ISBN end point to get result of the book
what data will you use from it? I am gonna use title,authors,category,description and raitings under volumeInfo key.   
Anything else that will help us understand what you are creating!

**Comment by trevorpreston** [comment]
This sounds good.  I haven’t used the google books api before.  Have you tried it and gotten data from it successfully yet?  Make sure you get that tested and working tonight!

Approved with trust that you’ll have tested this by the morning.  If you don’t have it working tonight, start thinking of new ideas.  We 100% need to have a tested working api by tomorrow!
