### ISSUE TITLE
Project Proposal

### ISSUE THREAD

**Issue by Byatoo** [js-penguins/JS-final-project#10]
Name of your app
"Not yet decided "
What the app will do?
"Most probably will be a job finder"
What API will you use? Include:
"Adzuna"
a link to the documentation
"https://api.adzuna.com/static/swagger-ui/index.html#!/adzuna "
an example endpoint
"http://api.adzuna.com/v1/api/property/gb/search/1?app_id={YOUR_APP_ID}&app_key={YOUR_APP_KEY}"
what data will you use from it?
"Not yet decided "

**Comment by trevorpreston** [comment]
Sounds like you are a bit uncertain if you want to do this.  Any update on what you plan to do?

**Comment by Byatoo** [comment]
Hi Trevor, 
Good morning, 
I really apologize for my late response. Yesterday I got too busy with my parents, was too tired afterward and went to sleep early. Actually, I've been testing many APIs for job search engine and most of them require to fill out an application and wait for some time to get the API endpoint along with the key. So I  might need your help finding an easy one to implement. 

In my project, I will be creating a single page application for job finding. the user will have to input two values into search boxes.
1- the user will type a job title.
2- the user will need to choose a city
3- the user then will get a list of job opportunities.
4- the user will click on one job to view the job details.
