### ISSUE TITLE
final project

### ISSUE THREAD

**Issue by Majdalmutairi** [js-penguins/JS-final-project#12]
Name of the APP: 
USD Rates

What the app will do?
Display real-time USD exchange rates with other currencies. 

What API will you use?
currencylayer
Link to the documentation:
https://currencylayer.com/documentation

An example endpoint:
http://www.apilayer.net/api/live?access_key=YOUR_ACCESS_KEY&format=1

what data will u use from it?
all data will be returned wall be need

**Comment by JackieCasper** [comment]
Sounds like a good idea 👍 can't wait to see it!
