### ISSUE TITLE
first Idea

### ISSUE THREAD

**Issue by Lameesaf** [js-penguins/JS-final-project#13]
Name of your app: Analyzing you
What the app will do? take a text then analyze it (maybe 
I will add speech to text so it will take a voice then then send the text to tone analyzer )
What API will you use?
tone analyzer: https://cloud.ibm.com/apidocs/tone-analyzer
speech to text: https://cloud.ibm.com/apidocs/speech-to-text
An example endpoin:
What data will you use from it? the text from speech to text and the output from tone analyzer

**Comment by Lameesaf** [comment]
An example endpoin:
https://gateway-wdc.watsonplatform.net/speech-to-text/api/v1/recognize
https://gateway-wdc.watsonplatform.net/tone-analyzer/api/v3/tone?version=2017-09-21&text=hello nice to meet you

**Comment by JackieCasper** [comment]
Sounds good! Getting the jquery ajax calls right may take some work with the headers and file uploads, try to get that down asap and make sure it works 👍
