### ISSUE TITLE
Find Event

### ISSUE THREAD

**Issue by Emtenan1** [js-penguins/JS-final-project#16]
**Name of your app**
Find your artist
**What the app will do?**
shows the information of the artist
**What API will you use?**
apiKey
**Link to the documentation**
https://www.theaudiodb.com/api_guide.php
**An example endpoint**
the information of the artist
**What data will you use from it?**
 Name of the artist, formed year, born year, style of the artist, accounts, mood, gender, country,
**Anything else that will help us understand what you are creating!**
I will create a page that contain search button for searching artist name and will shows the information about the artist

**Comment by JackieCasper** [comment]
Hey Emtenan,
From looking at the documentation this api may need to use oAuth. Have you tried making a request yet and getting back data? If so, using what endpoint?

**Comment by Emtenan1** [comment]
Dear Jackie,

Yes I tried, but it’s ask me the app url !

On 29 Apr 2019, at 8:05 PM, Jackie Casper <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey Emtenan,
From looking at the documentation this api may need to use oAuth. Have you tried making a request yet and getting back data? If so, using what endpoint?

**Comment by JackieCasper** [comment]
try putting in http://localhost:3000 - its a basic url to use for locally hosted apps

**Comment by Emtenan1** [comment]
Could you help me please, I can’t find the API

On 29 Apr 2019, at 8:17 PM, Jackie Casper <notifications@github.com<mailto:notifications@github.com>> wrote:


try putting in http://localhost:3000 - its a basic url to use for locally hosted apps
