### ISSUE TITLE
Final project ideal

### ISSUE THREAD

**Issue by RayanHakeem** [js-penguins/JS-final-project#17]
Name of your app : Currency exchange
What the app will do? Convert the Currency to another Currency 
What API will you use? To take the value of the Currency 
Link to the documentation : 
https://fixer.io/documentation
http://data.fixer.io/api/latest?access_key=807dbebc5d76a4b8e1e09be7a9c28bd1&format=1
What data will you use from it? value of the Currency

**Comment by JackieCasper** [comment]
Sounds like a good idea! And the API looks good too. Can't wait to see it 👍
