### ISSUE TITLE
green life

### ISSUE THREAD

**Issue by Lamya545** [js-penguins/JS-final-project#18]
- Name of your app : Green Life.

- What the app will do? Search For Healthy Recipes.

- What API will you use? https://api.edamam.com/

- Link to the documentation: https://developer.edamam.com/edamam-docs-recipe-api 

- An example endpoint: https://api.edamam.com/search?q=meat&app_id=fb5cb5b9&app_key=%201dc798218570438d0be2430d7e401473

- What data will you use from it? Recipes. 

- Anything else that will help us understand what you are creating!: trying to help people who trying to be healthy in simple way that they can find a Recipe!.

**Comment by JackieCasper** [comment]
Sounds like a good idea and the end point looks good 👍 can't wait to see it!
