### ISSUE TITLE
Final project proposal,Aljwharah

### ISSUE THREAD

**Issue by AljwharahAZ0** [js-penguins/JS-final-project#19]
•	Name of the app:
 **Finder logo**
•	What the app will do? 
People can find the logo for the companies by writing the domain of the company for example (google.com) it will retrieve the google log to the browser. 
•	What API will you use? Logo API
o	Link to the documentation:
[https://clearbit.com/docs?shell#logo-api](url)
o	An example endpoint
logo
o	What data will you use from it?
Search logo image for the specific domain  
In the main page, I will make a form, so the user can enter the domain name then press the button that will retrieve the logo image.  
It like google image search, easy way to find a logo for the company.

**Comment by JackieCasper** [comment]
Hi Aljwarah,
This API seems good and straight forward. Try to think about some ways to broaden the scope of the project a bit. Maybe users can have favorite icons that are stored in local storage? Approval pending - let me know what you think.

**Comment by AljwharahAZ0** [comment]
That's a good idea, so I can add saveIcons button to save it to local storage the show it in the main page

**Comment by JackieCasper** [comment]
👍 looking forward to seeing it
