### ISSUE TITLE
final project

### ISSUE THREAD

**Issue by raedalkhaldi** [js-penguins/JS-final-project#2]
Name of your app : Movies recommendation
What the app will do : simple algorithm to recommend the best movie for you.
a link to the documentation: https://developers.themoviedb.org/3/movies/get-movie-details
what data will you use from it?: Movies names

I want to create website to chose a movie for the user.

**Comment by trevorpreston** [comment]
Sounds good.

One thing to be aware of is that this API uses token auth.  There are two requests needed, first you need to request a token from the API then make another request with that token in the url to get the data.  *Try get this done first*.

I would recommend committing tonight/tomorrow to getting this to work.  Token auth can be different levels of challenging depending on how the API does it.

Approved with trust that you'll change API's if you can not get this working in the next day.
