### ISSUE TITLE
Currency conversion

### ISSUE THREAD

**Issue by AmeeraKhuzaim** [js-penguins/JS-final-project#20]
Name of your app? 
Currency conversion

What the app will do? 
There will be two drop down lists for currencies and an input text for rate
The user will choose the currency that he want from and to convert
And he will type the amount (rate)
He will press Convert button 
And after that the app will show the rate in the desired currency 

What API will you use?
Link to the documentation:
https://fixer.io/documentation

An example endpoint:
http://data.fixer.io/api/latest?access_key=5420222ad50073ff6264e341cd0a417b&format=1

Data will you use from it:
rate 
Anything else that will help us understand what you are creating!

**Comment by JackieCasper** [comment]
Sounds good! Looking forward to seeing it 👍
