### ISSUE TITLE
Update projecte 

### ISSUE THREAD

**Issue by Hoda90** [js-penguins/JS-final-project#22]
Name of your app  Holiday days 
What the app will do? show all holiday in country user chooses 
What API will you use? Include:  year , id country  code 
a link to the documentation
https://date.nager.at/api/v2/PublicHolidays/2017/AT
an example endpoint 
https://date.nager.at/api/v2/PublicHolidays/2017/AT
what data will you use from it?
to show all holidays in the country

**Comment by JackieCasper** [comment]
Sounds good 👍 looking forward to seeing it
