### ISSUE TITLE
Project Proposal

### ISSUE THREAD

**Issue by haithemalbetairi** [js-penguins/JS-final-project#3]
The app will be called: "Check yo Facts." It's going to be a customizable trivia game-night helper application.  It will be based on the Open Trivia API. 
Link: https://opentdb.com/api_config.php
Endpoint: https://opentdb.com/api.php?amount=10
Data used: So far I'm, probably gonna use all the data in the result. It contains the category, type, and difficulty of the question, along with the answer.

Think generic trivia game.

**Comment by JackieCasper** [comment]
sounds good 👍 can't wait to see it!
