### ISSUE TITLE
Final Project

### ISSUE THREAD

**Issue by Wa2eLjk** [js-penguins/JS-final-project#4]
Name of your app
significare
What the app will do?
mean recipes
What API will you use?
The MealDB
Link to the documentation
https://www.themealdb.com/api.php
An example endpoint
https://www.themealdb.com/api/json/v1/1/search.php?s=Montreal%20Smoked%20Meat
What data will you use from it?
all of it
Anything else that will help us understand what you are creating!
didn't have time to think, was going to research more on google analytics but ran out of time. but i think this is fun, plus who doesn't like to know how to make food

**Comment by trevorpreston** [comment]
Perfect.  👍
