### ISSUE TITLE
Final project proposal

### ISSUE THREAD

**Issue by Aalmonef** [js-penguins/JS-final-project#6]
App name: Shows Details

What the app will do?
Get the name of the show from the user and display the information of the show.

What API will you use?
- http://www.tvmaze.com/api#show-search
- http://api.tvmaze.com/search/people?q=lauren

what data will you use from it?
Shows details.

More info about the project:
The website will display the user all the information about a specific show the user want.

**Comment by trevorpreston** [comment]
Looks good!  TVmaze is a great API.   Looking forward to seeing it 👍
