### ISSUE TITLE
Final project 

### ISSUE THREAD

**Issue by FatimahAlsaigh** [js-penguins/JS-final-project#7]
Name of your app: qayem 
What the app will do: qayem is arabic word means tip. My app will contains a tips for sum restaurant in riyadh
What API will you use? https://developer.foursquare.com/
Link to the documentation
An example endpoint POST
My modification end-point
 https://api.foursquare.com/v2/venues/43695300f964a5208c291fe3/tips?client_id=DYY14B015HXMCWC5GJWSJKORT1YBSFAAMULSZJWFELQK4XHU&client_secret=3GTLL3PV30SCJK5QLF0UCKA0HMCFQYEEJ3PGE5SHHHBC1YUN&v=20190429

**Comment by trevorpreston** [comment]
Oooo interesting, I haven't seen the FourSquare API used before. It looks good to me!  Looking forward to it 👍
