### ISSUE TITLE
Project Proposal

### ISSUE THREAD

**Issue by neeomy** [js-penguins/JS-final-project#8]
Name of your app
puzzle game 
    What the app will do?
turn any photo to a puzzle game and try to solve it befor the timer end.
    What API will you use?
https://api.unsplash.com/photos/random
        Link to the documentation
https://unsplash.com/documentation#get-a-random-photo
        An example endpoint
https://api.unsplash.com/photos/random/?client_id=36ebb5cf213460de3e21cb70ea266e6b3070c9d8df081556f8010168f6a573b3
        What data will you use from it?
the photos only
    Anything else that will help us understand what you are creating!
it will be a small browser web game .

**Comment by JackieCasper** [comment]
Sounds good! Can't wait to see it 👍
