### ISSUE TITLE
ahad alanazi

### ISSUE THREAD

**Issue by ahadalmu** [js-penguins/JS-final-project#9]
Name of your app
Game of thorns Information.

What the app will do?
it will provide information , photo and quotes from GOT.
 
What API will you use?
https://anapioficeandfire.com/
https://github.com/wsizoo/game-of-thrones-quotes // to be hones I search about APIs for GOT and I fond  this in github it is providing a random quotes , but I don't know how to use it.

Link to the documentation;
https://anapioficeandfire.com/Documentation

An example endpoint
https://anapioficeandfire.com/api/houses/378

What data will you use from it?
most of it.

Anything else that will help us understand what you are creating!
I want to create page that take output from user and proved information , photos and quotes.

**Comment by JackieCasper** [comment]
Sounds great! Can't wait to see it! 👍
